version: "3.8"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: aviary-db
      MYSQL_USER: aviaryAdmin
      MYSQL_PASSWORD: av1aRy@adm1n
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: Asia/Tokyo
    volumes:
      - ./data/volumes/data/mysql-data:/var/lib/mysql
    networks:
      - avairy-network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --requirepass abcd1234
    networks:
      - avairy-network

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: qa_db
      POSTGRES_USER: twave_01
      POSTGRES_PASSWORD: twave_01password
    networks:
      - avairy-network

  solr:
    image: solr:9.8.1
    ports:
      - "8984:8983"
    networks:
      - avairy-network

networks:
  avairy-network:
